export const SET_MILJOLIST = 'SET_MILJOLIST';
export const SET_BREVPAKKELIST = 'SET_BREVPAKKELIST';
export const SET_BREVMALLIST = 'SET_BREVMALLIST';
export const SET_BREVINFO = 'SET_BREVINFO';
export const SET_BREVDATALIST = 'SET_BREVDATALIST';
export const SET_BREVDATA = 'SET_BREVDATA';
export const SET_MILJO = 'SET_MILJO';
export const SET_BREVPAKKE = 'SET_BREVPAKKE';
export const SET_BREVMAL = 'SET_BREVMAL';
export const CHANGE_BREVDATA_XML = 'CHANGE_BREVDATA_XML';
export const CHANGE_BESKRIVELSE = 'CHANGE_BESKRIVESLSE';
export const SET_DOKUMENT = 'SET_DOKUMENT';
export const ADD_ERROR='ADD_ERROR';
export const SET_IS_REDIGERT_EXTERNAL='SET_IS_REDIGERT_EXTERNAL';
export const SET_SAMMENLIGN_INFO='SET_SAMMENLIGN_INFO';
export const SET_SHOW_MODAL='SET_SHOW_MODAL';
//Her skal liste alle actions som skal kalle på reducere
