export const SET_MILJOLIST = 'SET_MILJOLIST';
export const SET_BREVPAKKELIST = 'SET_BREVPAKKELIST';
export const SET_BREVMALLIST = 'SET_BREVMALLIST';
export const SET_BREVINFO = 'SET_BREVINFO';
export const SET_BREVDATALIST = 'SET_BREVDATALIST';
export const SET_BREVDATA = 'SET_BREVDATA';
export const SET_MILJO = 'SET_MILJO';
export const SET_BREVPAKKE = 'SET_BREVPAKKE';
export const SET_BREVMAL = 'SET_BREVMAL';
export const CHANGE_BREVDATA_XML = 'CHANGE_BREVDATA_XML';
export const CHANGE_BESKRIVELSE = 'CHANGE_BESKRIVESLSE';
export const SET_DOKUMENT = 'SET_DOKUMENT';
export const ADD_ERROR='ADD_ERROR';
export const SAVE_BREVDATA = 'SAVE_BREVDATA'; //action creator
export const SET_VERSJON = 'SET_VERSJON';
export const SET_REGRESSION_BREVMALLIST = 'SET_REGRESSION_BREVMALLIST';
export const SET_REGRESSION_BREVDATALIST = 'SET_REGRESSION_BREVDATALIST';
export const SET_REGRESSION_BREVINFO = 'SET_REGRESSION_BREVINFO';
export const SET_REGRESSION_BREVPAKKELIST = 'SET_REGRESSION_BREVPAKKELIST';
export const SET_REGRESSION_MILJOLIST = 'SET_REGRESSION_MILJOLIST';
export const SET_REGRESSION_BREVMAL = 'SET_REGRESSION_BREVMAL';
export const SET_REGRESSION_BREVPAKKE = 'SET_REGRESSION_BREVPAKKE';
export const SET_REGRESSION_MILJO = 'SET_REGRESSION_MILJO';

//Her skal liste alle actions som skal kalle på reducere
