kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: ezbrev-frontend-q4
  namespace: teamdokumenthandtering
  labels:
    team: teamdokumenthandtering
  annotations:
    nais.io/run-as-user: "101" # nginx
    nais.io/read-only-file-system: "false" # need write /etc/nginx/conf.d
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
spec:
  env:
    - name: EZBREV_HOST_URL
      value: {{ EZBREV_HOST_URL }}
  image: {{ image }}
  ingresses:
    - {{ INGRESSES }}
  leaderElection: true
  liveness:
    path: internal/isAlive
    port: 8080
    initialDelay: 30
    failureThreshold: 10
  port: 8080
  prometheus:
    enabled: true
    path: /actuator/prometheus
  readiness:
    path: internal/isReady
    port: 8080
    initialDelay: 30
    timeout: 3
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  webproxy: true
