name: Build app

on:
  workflow_call:
    outputs:
      tag:
        description: "Build tag"
        value: ${{ jobs.build-frontend.outputs.tag }}
      image:
        description: "GAR image"
        value: ${{ jobs.build-frontend.outputs.image }}

jobs:
  build-frontend:
    name: Build frontend with node
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.docker-build-push.outputs.tag }}
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      # prebuild
      - name: Checkout code
        uses: actions/checkout@v4
        # checkout gir shallow copy - fetch-depth: 0 vil tilgjengeliggjøre tags
        with:
          fetch-depth: 0
      - name: Set up Node v16
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Cache ~/.npm
        id: cache-npm-repository
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # npm build
      - name: Install dependencies
        run: npm ci -q
        env:
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Run tests
        run: npm test -- --watchAll=false
      - name: Build application
        run: npm run build
      # docker build using trivy
      - name: Build and push to GAR
        if: ${{ github.actor != 'dependabot[bot]' }}
        id: docker-build-push
        uses: nais/docker-build-push@v0
        with:
          team: teamdokumenthandtering
          pull: true
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
        env:
          ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}