name: Build app

on:
  workflow_call:
    outputs:
      build-tag:
        description: "Build tag"
        value: ${{ jobs.build-frontend.outputs.build-tag }}

jobs:
  build-frontend:
    name: Build frontend with node
    runs-on: ubuntu-latest
    outputs:
      build-tag: ${{ steps.generate-build-tag.outputs.build-tag }}
    steps:
      # prebuild
      - name: Checkout code
        uses: actions/checkout@v3
        # checkout gir shallow copy - fetch-depth: 0 vil tilgjengeliggjøre tags
        with:
          fetch-depth: 0
      - name: Set up Node v16
        uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"
      - name: Cache ~/.npm
        id: cache-npm-repository
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # build tag
      - name: Generate build tag
        id: generate-build-tag
        run: |
          base_number=$(git describe --abbrev=0 --tags | awk -F \. {'$1++;print $1'})
          echo "Build base_number=$base_number"
          if ! [[ $base_number =~ ^[0-9]+$ ]]; then
            build_tag=$((echo "1" && git rev-parse --short HEAD) | paste -s -d'-'); 
          else 
            build_tag=$((echo $base_number && git rev-parse --short HEAD) | paste -s -d'-'); 
          fi
          echo "Generated build-tag=$build_tag"
          echo "build-tag=$(echo $build_tag)" >> $GITHUB_OUTPUT
      # npm build
      - name: Install dependencies
        run: npm ci -q
      - name: Run tests
        run: npm test -- --watchAll=false
      - name: Build application
        run: npm run build
      # docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.generate-build-tag.outputs.build-tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        # Temp fix for voksende cache
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
