name: Build, deploy feature

on:
  workflow_call:

jobs:
  build-feature:
    uses: ./.github/workflows/build-frontend.yml
    secrets: inherit
  deploy-feature:
    uses: navikt/dok-workflows/.github/workflows/deploy-all-dev-gar.yml@main
    needs: build-feature
    secrets: inherit
    with:
      image: ${{ needs.build-feature.outputs.image }}
