name: Build, deploy dev feature

on:
  push:
    branches-ignore:
      - main
      - master
      - 'dependabot/**'

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-deploy-feature-frontend.yml
    secrets: inherit
