name: Build, deploy dev, draft main

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    permissions:
      contents: write
      packages: write
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/build-deploy-main-frontend.yml
    secrets: inherit
